### ISSUE TITLE
setup.py url arg does not match with repository name 

### ISSUE THREAD

**Issue by reduxionist** [wesleylima/django-rest-framework-firebase#1]
It's a tiny little thing but it breaks the link from PyPI to the sourecode; normally I'd open a PR but I think the url passed to setup is more descriptive than the current project name so I'm just opening an issue to bring it to your attention instead. Thanks for sharing your code! :smile:

**Comment by wesleylima** [comment]
Thanks for catching this! I just changed the URL on setup since it's the most used name throughout.
