### ISSUE TITLE
broken example

### ISSUE THREAD

**Issue by AdrienLemaire** [wesleylima/django-rest-framework-firebase#2]
README:
```
REST_FRAMEWORK = {
  ...
  'DEFAULT_AUTHENTICATION_CLASSES': (
    'rest_framework_firebase_auth.authentication.Firebaseuthentication',
  )
  ...
}
```
The package name seems to be `rest_framework_firebase` (without `_auth`), so I'm assuming the correct example should be:

```
REST_FRAMEWORK = {
  ...
  'DEFAULT_AUTHENTICATION_CLASSES': (
    'rest_framework_firebase.authentication.Firebaseuthentication',
  )
  ...
}
```

**Comment by AdrienLemaire** [comment]
Also, why did you use the name `Firebaseuthentication` instead of `FirebaseAuthentication` ?

**Comment by wesleylima** [comment]
Good catch on the documentation and class name. Wasn't like that for a reason, just a nasty type-o.
