### ISSUE TITLE
AttributeError 'Firebaseuthentication' object has no attribute 'has_permission'

### ISSUE THREAD

**Issue by AdrienLemaire** [wesleylima/django-rest-framework-firebase#3]
Hi, and thank you for making this plugin. Unfortunately, it doesn't seem to be working at all for me. 
Is it not supposed to work with viewsets ? I'm using ModelViewSet and ReadOnlyModelViewSet.

Django==2.0.6
djangorestframework==3.8.2
djangorestframework-firebase==0.1.2
python-firebase==1.2

**Comment by pm990320** [comment]
I ran into a similar issue - make sure you are definitely setting `DEFAULT_AUTHENTICATION_CLASSES` and not `DEFAULT_PERMISSION_CLASSES` (which is what's on http://www.django-rest-framework.org/#example)

**Comment by AdrienLemaire** [comment]
I went for a custom authentication class, so not using this package anymore. Anyways, I was probably misusing DEFAULT_PERMISSION_CLASSES at the time as you suggested.
Closing.
